/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceBase`
  ADD COLUMN `deviceFlag` INT NULL;

CREATE INDEX `deviceType_i`
  ON `MHJDeviceBase` (`deviceType`);

CREATE INDEX `deviceFlag_i`
  ON `MHJDeviceBase` (`deviceFlag`);

UPDATE `schema_version`
  SET `version` = 9, `migration` = 1
  WHERE `name` = '';

