/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceAuthorize`
  ADD COLUMN `child` BIGINT UNSIGNED NULL;

CREATE INDEX `child_i`
  ON `MHJDeviceAuthorize` (`child`);

UPDATE `schema_version`
  SET `version` = 20, `migration` = 1
  WHERE `name` = '';

