/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceBase`
  DROP COLUMN `softVer`,
  DROP COLUMN `newSoftUrl`,
  DROP COLUMN `newSoftVer`;

UPDATE `schema_version`
  SET `migration` = 0
  WHERE `name` = '';

