/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceChild`
  ADD COLUMN `defineChangeTime` DATETIME NULL;

UPDATE `schema_version`
  SET `version` = 24, `migration` = 1
  WHERE `name` = '';

