/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `user_entity`
  ADD COLUMN `usertoken` CHAR(255) NULL;

ALTER TABLE `admin_entity`
  ADD COLUMN `adminToken` CHAR(255) NULL;

UPDATE `schema_version`
  SET `version` = 14, `migration` = 1
  WHERE `name` = '';

