/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `user_entity`
  MODIFY COLUMN `UserTitle` LONGTEXT NOT NULL;

UPDATE `schema_version`
  SET `migration` = 0
  WHERE `name` = '';

