/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `user_entity`
  ADD COLUMN `UserTitle` LONGTEXT NULL;

CREATE TABLE `MHJDeviceChild` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `device` BIGINT UNSIGNED NOT NULL,
  `keyID` BIGINT UNSIGNED NOT NULL,
  `Name` TEXT NOT NULL,
  `user` INT(11) NOT NULL,
  `KyeDefine` INT UNSIGNED NULL)
 ENGINE=InnoDB;

CREATE INDEX `device_i`
  ON `MHJDeviceChild` (`device`);

CREATE INDEX `keyID_i`
  ON `MHJDeviceChild` (`keyID`);

CREATE INDEX `user_i`
  ON `MHJDeviceChild` (`user`);

/*
ALTER TABLE `MHJDeviceChild`
  ADD CONSTRAINT `MHJDeviceChild_device_fk`
    FOREIGN KEY (`device`)
    REFERENCES `MHJDeviceBase` (`id`),
  ADD CONSTRAINT `MHJDeviceChild_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `user_entity` (`id`)
*/

UPDATE `schema_version`
  SET `version` = 6, `migration` = 1
  WHERE `name` = '';

