/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceActivation`
  ADD COLUMN `DeviceName` TEXT NULL;

UPDATE `schema_version`
  SET `version` = 8, `migration` = 1
  WHERE `name` = '';

