/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceVirtualDefine`
  MODIFY COLUMN `defineTime` DATETIME NOT NULL;

UPDATE `schema_version`
  SET `migration` = 0
  WHERE `name` = '';

