/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceChild`
  DROP COLUMN `KyeDefine`;

UPDATE `schema_version`
  SET `migration` = 0
  WHERE `name` = '';

