/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `MHJDeviceAuthorize`;

DROP TABLE IF EXISTS `MHJDeviceActivation`;

DROP TABLE IF EXISTS `MHJDeviceVirtualDefine`;

DROP TABLE IF EXISTS `MHJDeviceChild`;

DROP TABLE IF EXISTS `MHJDeviceBase`;

CREATE TABLE IF NOT EXISTS `schema_version` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY,
  `version` BIGINT UNSIGNED NOT NULL,
  `migration` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

DELETE FROM `schema_version`
  WHERE `name` = '';

CREATE TABLE `MHJDeviceBase` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `deviceID` INT NOT NULL,
  `idsecurity` INT NULL,
  `deviceType` INT NOT NULL,
  `virtualKeyCount` INT NULL,
  `virtualKeyDefine` CHAR(255) NULL,
  `switchKeyfCount` INT NULL,
  `security` CHAR(32) NULL,
  `createDate` DATETIME NOT NULL,
  `createUser` TEXT NOT NULL,
  `createVerification` TINYINT(1) NULL,
  `productionDate` DATETIME NULL,
  `productionUser` TEXT NULL,
  `activationDate` DATETIME NULL,
  `deviceFlag` INT NULL)
 ENGINE=InnoDB;

CREATE INDEX `deviceID_i`
  ON `MHJDeviceBase` (`deviceID`);

CREATE INDEX `idsecurity_i`
  ON `MHJDeviceBase` (`idsecurity`);

CREATE INDEX `deviceType_i`
  ON `MHJDeviceBase` (`deviceType`);

CREATE INDEX `deviceFlag_i`
  ON `MHJDeviceBase` (`deviceFlag`);

CREATE TABLE `MHJDeviceChild` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `device` BIGINT UNSIGNED NOT NULL,
  `keyID` BIGINT UNSIGNED NOT NULL,
  `Name` TEXT NOT NULL,
  `user` INT(11) NOT NULL,
  `KeyDefine` INT UNSIGNED NULL,
  `state` INT UNSIGNED NULL,
  `defineChangeTime` DATETIME NULL,
  `ImgIco` TEXT NULL)
 ENGINE=InnoDB;

CREATE INDEX `device_i`
  ON `MHJDeviceChild` (`device`);

CREATE INDEX `keyID_i`
  ON `MHJDeviceChild` (`keyID`);

CREATE INDEX `user_i`
  ON `MHJDeviceChild` (`user`);

CREATE TABLE `MHJDeviceVirtualDefine` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `deviceKey` BIGINT UNSIGNED NOT NULL,
  `targetKey` BIGINT UNSIGNED NOT NULL,
  `targetNewState` INT UNSIGNED NOT NULL,
  `defineTime` DATETIME NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `deviceKey_i`
  ON `MHJDeviceVirtualDefine` (`deviceKey`);

CREATE INDEX `targetKey_i`
  ON `MHJDeviceVirtualDefine` (`targetKey`);

CREATE TABLE `MHJDeviceActivation` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `device` BIGINT UNSIGNED NOT NULL,
  `Date` DATETIME NOT NULL,
  `ip` TEXT NOT NULL,
  `mac` TEXT NULL,
  `user` INT(11) NOT NULL,
  `DeviceName` TEXT NULL,
  `softVer` TEXT NULL,
  `newSoftUrl` TEXT NULL,
  `newSoftVer` TEXT NULL)
 ENGINE=InnoDB;

CREATE INDEX `device_i`
  ON `MHJDeviceActivation` (`device`);

CREATE INDEX `user_i`
  ON `MHJDeviceActivation` (`user`);

CREATE TABLE `MHJDeviceAuthorize` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `device` BIGINT UNSIGNED NOT NULL,
  `child` BIGINT UNSIGNED NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `user` INT(11) NOT NULL,
  `giveUser` INT(11) NOT NULL,
  `giveType` INT NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `device_i`
  ON `MHJDeviceAuthorize` (`device`);

CREATE INDEX `child_i`
  ON `MHJDeviceAuthorize` (`child`);

CREATE INDEX `user_i`
  ON `MHJDeviceAuthorize` (`user`);

CREATE INDEX `giveUser_i`
  ON `MHJDeviceAuthorize` (`giveUser`);

INSERT IGNORE INTO `schema_version` (
  `name`, `version`, `migration`)
  VALUES ('', 25, 0);

