/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE `MHJDeviceAuthorize` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `device` BIGINT UNSIGNED NOT NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `user` INT(11) NOT NULL,
  `giveUser` INT(11) NOT NULL,
  `giveType` INT NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `device_i`
  ON `MHJDeviceAuthorize` (`device`);

CREATE INDEX `user_i`
  ON `MHJDeviceAuthorize` (`user`);

CREATE INDEX `giveUser_i`
  ON `MHJDeviceAuthorize` (`giveUser`);

/*
ALTER TABLE `MHJDeviceAuthorize`
  ADD CONSTRAINT `MHJDeviceAuthorize_device_fk`
    FOREIGN KEY (`device`)
    REFERENCES `MHJDeviceBase` (`id`),
  ADD CONSTRAINT `MHJDeviceAuthorize_user_fk`
    FOREIGN KEY (`user`)
    REFERENCES `user_entity` (`id`),
  ADD CONSTRAINT `MHJDeviceAuthorize_giveUser_fk`
    FOREIGN KEY (`giveUser`)
    REFERENCES `user_entity` (`id`)
*/

UPDATE `schema_version`
  SET `version` = 5, `migration` = 1
  WHERE `name` = '';

