/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP INDEX `Key_i` ON `MHJDeviceVirtualDefine`;

ALTER TABLE `MHJDeviceVirtualDefine`
  MODIFY COLUMN `deviceKey` BIGINT UNSIGNED NOT NULL,
  DROP COLUMN `Key`;

UPDATE `schema_version`
  SET `migration` = 0
  WHERE `name` = '';

