/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceBase`
  ADD COLUMN `virtualKyeCount` INT NULL,
  ADD COLUMN `virtualKyeDefine` CHAR(255) NULL,
  ADD COLUMN `switchKyeCount` INT NULL;

UPDATE `schema_version`
  SET `version` = 3, `migration` = 1
  WHERE `name` = '';

