/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceChild`
  ADD COLUMN `KeyDefine` INT UNSIGNED NULL;

UPDATE `schema_version`
  SET `version` = 7, `migration` = 1
  WHERE `name` = '';

