/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

/*
ALTER TABLE `MHJDeviceActivation`
  DROP FOREIGN KEY `MHJDeviceActivation_device_fk`,
  DROP FOREIGN KEY `MHJDeviceActivation_user_fk`
*/

/*
ALTER TABLE `MHJDeviceAuthorize`
  DROP FOREIGN KEY `MHJDeviceAuthorize_device_fk`,
  DROP FOREIGN KEY `MHJDeviceAuthorize_user_fk`,
  DROP FOREIGN KEY `MHJDeviceAuthorize_giveUser_fk`
*/

ALTER TABLE `user_entity`
  ADD COLUMN `usertitle` LONGTEXT NULL,
  ADD COLUMN `userToken` CHAR(255) NULL,
  ADD COLUMN `tokenReplaceTime` DATETIME NULL;

/*
ALTER TABLE `MHJDeviceChild`
  DROP FOREIGN KEY `MHJDeviceChild_device_fk`,
  DROP FOREIGN KEY `MHJDeviceChild_user_fk`
*/

UPDATE `schema_version`
  SET `version` = 12, `migration` = 1
  WHERE `name` = '';

