/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE `MHJDeviceVirtualDefine` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `Key` BIGINT UNSIGNED NOT NULL,
  `targetKey` BIGINT UNSIGNED NOT NULL,
  `targetNewState` INT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `Key_i`
  ON `MHJDeviceVirtualDefine` (`Key`);

CREATE INDEX `targetKey_i`
  ON `MHJDeviceVirtualDefine` (`targetKey`);

/*
ALTER TABLE `MHJDeviceAuthorize`
  DROP FOREIGN KEY `MHJDeviceAuthorize_child_fk`
*/

/*
ALTER TABLE `MHJDeviceVirtualDefine`
  ADD CONSTRAINT `MHJDeviceVirtualDefine_Key_fk`
    FOREIGN KEY (`Key`)
    REFERENCES `MHJDeviceChild` (`id`),
  ADD CONSTRAINT `MHJDeviceVirtualDefine_targetKey_fk`
    FOREIGN KEY (`targetKey`)
    REFERENCES `MHJDeviceChild` (`id`)
*/

UPDATE `schema_version`
  SET `version` = 21, `migration` = 1
  WHERE `name` = '';

