/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceVirtualDefine`
  ADD COLUMN `deviceKey` BIGINT UNSIGNED NULL;

CREATE INDEX `deviceKey_i`
  ON `MHJDeviceVirtualDefine` (`deviceKey`);

UPDATE `schema_version`
  SET `version` = 23, `migration` = 1
  WHERE `name` = '';

