/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `user_entity`
  ADD COLUMN `userToken` CHAR(255) NULL;

UPDATE `schema_version`
  SET `version` = 15, `migration` = 1
  WHERE `name` = '';

