/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceChild`
  ADD COLUMN `ImgIco` TEXT NULL;

UPDATE `schema_version`
  SET `version` = 25, `migration` = 1
  WHERE `name` = '';

