/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE `MHJDeviceBase`
  ADD COLUMN `virtualKeyCount` INT NULL,
  ADD COLUMN `virtualKeyDefine` CHAR(255) NULL,
  ADD COLUMN `switchKeyfCount` INT NULL;

UPDATE `schema_version`
  SET `version` = 10, `migration` = 1
  WHERE `name` = '';

